#############
### Theme ###
#############

# animation = windows, 0
# animation = fade, 0
# animation = workspaces, 0

general {
  gaps_in = 3
  gaps_out = 6
  # border_size = 2
  # col.active_border = rgb(1d2021)
  # col.inactive_border = rgb(1d2021)
  layout = master
  resize_on_border = false
}

decoration {
  rounding = 0

  blur {
    enabled = yes
    size = 8
    passes = 2
  }
}

dwindle {
  force_split = 2
}
