####################
### Window Rules ###
####################

windowrule {
  name = Emacs
  match:class = Emacs

  workspace = 1
}

windowrule {
  name = DEV Browser
  match:class = google-chrome

  workspace = 2
}

windowrule {
  name = Coding Agent
  match:initial_title = opencode

  workspace = 3
}

windowrule {
  name = Lazygit
  match:initial_title = lazygit

  workspace = 4
}

windowrule {
  name = Main Browser
  match:class = helium

  workspace = 9
  focus_on_activate = true
}

windowrule {
  name = Steam
  match:class = steam

  workspace = 10
}
