[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
option_as_alt = "OnlyLeft"

decorations = "Buttonless"

opacity = 0.7
blur = true

[font]
normal.family = "Hack Nerd Font Mono"
size = 14
